language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t seoseokwon/valonity -f ./client/Dockerfile.dev ./client

script:
  # - docker run -e CI=true seoseokwon/valonity npm run test

after_success:
  - docker build -t seoseokwon/docker-frontend ./client 
  - docker build -t seoseokwon/docker-backend  ./server 
  - docker build -t seoseokwon/docker-nginx    ./nginx 

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push seoseokwon/docker-frontend  
  - docker push seoseokwon/docker-backend
  - docker push seoseokwon/docker-nginx    


deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: valonity-app
  env: Valonity-app-env
  bucket_name: elasticbeanstalk-ap-northeast-1-351996596363
  bucket_path: valonity-app
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY