version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    # 기본 데이터디렉터리 "/var/lib/postgresql/data" 
    volumes:
      - ./data:/var/lib/postgresql/data
  # server:
  #   build: ./server
  #   container_name: server
  #   restart: always
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - /usr/src/app/node_modules
  #     - ./server:/usr/src/app
  #   depends_on:
  #     - db
  # client:
  #   build: ./client
  #   container_name: client
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /usr/src/app/node_modules
  #     - ./client:/usr/src/app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true
  #   depends_on:
  #     - server
